language: r
notifications:
  slack:
    secure: QpfZCc73xIapX3epB/o9vKXfgEsce5OjQxn2y6AVq0IkhnoZEBKNXPCZTrvX9FpZZaFSQwqjuZvH+0yMFSajMNsyOf2l1HGDzdg+CP4ZTZgL/Kjjlfx8DHIJzHr8dLpCaPWmGZ/vOmqUffSmbFiqRf0MeWFtPD3yNZgDHvX7m+k=
